name = "levain-worker"
main = "worker/index.js"
compatibility_date = "2024-09-01"

[vars]
ALLOWED_ORIGIN = "https://heee.github.io"

[[d1_databases]]
binding = "DB"
database_name = "levain-db"
database_id = "27f236a5-a4c2-4846-ba42-3463bad9d202"
